language: generic
sudo: required
services: 
  - docker 

before_install:
          - docker build -t rostmart/docker-react -f Dockerfile.dev .
script:
          - docker run -e CI=true rostmart/docker-react npm run test
