language: generic
sudo: required
services: 
  - docker 

before_install:
          - docker build -f -t rostmart/docker-react Dockerfile.dev . 
script:
          - docker run -e CI=true rostmart/docker-react npm run test
